server:
  port: 8082

spring:
  application:
    name: post-service
  profiles:
    active: prod

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.23.9.30:3306/glue
    username: root
    password: jeong2160
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  # elastic
  elasticsearch:
    username: gcu-002
    password: glue2024!
    uris: https://8063c2e7a91f4814b6c492ee9cc9283c.us-west-2.aws.found.io:443

# elastic search
elasticsearch:
  api-key: WjBBbGFJOEJibng1TUN3SkphZG06M1J1bFJ3dmtTTENZZndfUjBrTVA5QQ==